name: Update Test Times Data

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3  # Updated to the latest version
    
    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to the latest version
      with:
        python-version: '3.x'
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@master
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager selenium-wire undetected-chromedriver

    - name: Run scraper
      env:
        LICENSE_NUMBER: ${{ secrets.LICENSE_NUMBER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python scripts/scraper.py
        
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add data.json  # Ensure this path is correct
        git commit -m "Update test times data" || exit 0
        git push
