name: Update Test Times Data

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@master
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install webdriver_manager
        pip install fake-useragent
        pip install requests
        pip install beautifulsoup4
        pip install free-proxy

    - name: Run scraper
      env:
        LICENSE_NUMBER: ${{ secrets.LICENSE_NUMBER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python scripts/scraper.py
